import Header from '@/components/Layout/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Layout/Footer'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '/*BLOG*/',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir='rtl'>
   <Head></Head>
      <body >
        <Header/>
        <div  className={`${inter.variable} font-sans`}>
          {children}
          </div>
        
        <Footer />
        </body>
 
    </html>
  )
}
